In [2]:
# Import Library
import pandas as pd

In [3]:
#Import the files to Google Colab
url = 'https://raw.githubusercontent.com/rc-dbe/bigdatacertification/master/dataset/churn_trasnsformed_new.csv'
df_csv = pd.read_csv(url, sep=',',)

# Show 10 first Row
df_csv.head()

,Unnamed: 0,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,...,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,1,1,...,0,1,0,1,0,0,1,2985,2985.0,0
1,1,1,0,0,1,1,0,0,1,34,...,1,0,1,0,0,1,0,5695,18895.0,0
2,2,1,0,0,1,1,0,0,1,2,...,0,1,0,1,0,1,0,5385,10815.0,1
3,3,1,0,0,1,1,0,0,1,45,...,1,0,1,0,0,1,1,423,184075.0,0
4,4,0,1,0,1,1,0,0,1,2,...,0,1,0,1,0,0,1,707,15165.0,1

In [4]:
# Remove "Unnamed:O" Coloumn
df = df_csv.drop("Unnamed: 0", axis=1)
df.head()

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges,Churn
0,0,1,0,1,0,1,0,1,1,0,...,0,1,0,1,0,0,1,2985,2985.0,0
1,1,0,0,1,1,0,0,1,34,1,...,1,0,1,0,0,1,0,5695,18895.0,0
2,1,0,0,1,1,0,0,1,2,1,...,0,1,0,1,0,1,0,5385,10815.0,1
3,1,0,0,1,1,0,0,1,45,0,...,1,0,1,0,0,1,1,423,184075.0,0
4,0,1,0,1,1,0,0,1,2,1,...,0,1,0,1,0,0,1,707,15165.0,1

In [5]:
# Check the Data Infomation
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 46 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender_0            7043 non-null   int64
 1   gender_1            7043 non-null   int64
 2   SeniorCitizen_0     7043 non-null   int64
 3   SeniorCitizen_1     7043 non-null   int64
 4   Partner_0           7043 non-null   int64
 5   Partner_1           7043 non-null   int64
 6   Dependents_0        7043 non-null   int64
 7   Dependents_1        7043 non-null   int64
 8   tenure              7043 non-null   int64
 9   PhoneService_0      7043 non-null   int64
 10  PhoneService_1      7043 non-null   int64
 11  MultipleLines_0     7043 non-null   int64
 12  MultipleLines_1     7043 non-null   int64
 13  MultipleLines_2     7043 non-null   int64
 14  InternetService_0   7043 non-null   int64
 15  InternetService_1   7043 non-null   int64
 16  InternetService_2   7043 non-null   int64
 17  OnlineSecurity_0    7043 non-null   int64
 18  OnlineSecurity_1    7043 non-null   int64
 19  OnlineSecurity_2    7043 non-null   int64
 20  OnlineBackup_0      7043 non-null   int64
 21  OnlineBackup_1      7043 non-null   int64
 22  OnlineBackup_2      7043 non-null   int64
 23  DeviceProtection_0  7043 non-null   int64
 24  DeviceProtection_1  7043 non-null   int64
 25  DeviceProtection_2  7043 non-null   int64
 26  TechSupport_0       7043 non-null   int64
 27  TechSupport_1       7043 non-null   int64
 28  TechSupport_2       7043 non-null   int64
 29  StreamingTV_0       7043 non-null   int64
 30  StreamingTV_1       7043 non-null   int64
 31  StreamingTV_2       7043 non-null   int64
 32  StreamingMovies_0   7043 non-null   int64
 33  StreamingMovies_1   7043 non-null   int64
 34  StreamingMovies_2   7043 non-null   int64
 35  Contract_0          7043 non-null   int64
 36  Contract_1          7043 non-null   int64
 37  Contract_2          7043 non-null   int64
 38  PaperlessBilling_0  7043 non-null   int64
 39  PaperlessBilling_1  7043 non-null   int64
 40  PaymentMethod_0     7043 non-null   int64
 41  PaymentMethod_1     7043 non-null   int64
 42  PaymentMethod_2     7043 non-null   int64
 43  MonthlyCharges      7043 non-null   int64
 44  TotalCharges        7043 non-null   float64
 45  Churn               7043 non-null   int64
dtypes: float64(1), int64(45)
memory usage: 2.5 MB

In [6]:
#Import MinMax Scaler
from sklearn.preprocessing import MinMaxScaler

# initialize min-max scaler
mm_scaler = MinMaxScaler()
column_names = df.columns.tolist()
column_names.remove('Churn')

# Transform all attributes
df[column_names] = mm_scaler.fit_transform(df[column_names])
df.sort_index(inplace=True)
df.head()

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges,Churn
0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.013889,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.250169,0.003420,0
1,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.472222,1.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.478745,0.021766,0
2,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.452598,0.012449,1
3,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.625000,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.034076,0.212235,0
4,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.058030,0.017465,1

In [7]:
# Selecting the Feature, by remove the unused feature
feature = ['Churn']
train_feature = df.drop(feature, axis=1)

# Set The Target
train_target = df["Churn"]

In [8]:
# Show the Feature
train_feature.head(5)

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_0,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges
0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.013889,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.250169,0.003420
1,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.472222,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.478745,0.021766
2,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.452598,0.012449
3,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.625000,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.034076,0.212235
4,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.058030,0.017465

In [9]:
# Split Data
from sklearn.model_selection import train_test_split, cross_val_score
X_train, X_test, y_train, y_test = train_test_split(train_feature ,train_target, shuffle = True, test_size=0.9, random_state=1)

In [10]:
# Show the training data
X_train.head()

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_0,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges
4342,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.722222,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.503205,0.357814
775,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.000000,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.931680,0.930030
4871,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.805556,1.0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.061825,0.049571
4648,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.057692,0.000144
5209,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.000000,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.925776,0.090524

In [11]:
# Import Library
from sklearn.neural_network import MLPClassifier

# Fitting Model
mlp = MLPClassifier(hidden_layer_sizes=(5), activation = 'relu', solver = 'adam',max_iter= 10000, verbose = True)
mlp = mlp.fit(X_train,y_train)

# Prediction to Test Dataset
y_predmlp = mlp.predict(X_test)

Iteration 1, loss = 0.63280685
Iteration 2, loss = 0.62313025
Iteration 3, loss = 0.61540485
Iteration 4, loss = 0.60793417
Iteration 5, loss = 0.60087191
Iteration 6, loss = 0.59493626
Iteration 7, loss = 0.58891334
Iteration 8, loss = 0.58327804
Iteration 9, loss = 0.57818736
Iteration 10, loss = 0.57339075
Iteration 11, loss = 0.56833953
Iteration 12, loss = 0.56384062
Iteration 13, loss = 0.55910647
Iteration 14, loss = 0.55448083
Iteration 15, loss = 0.54995801
Iteration 16, loss = 0.54602238
Iteration 17, loss = 0.54179882
Iteration 18, loss = 0.53741702
Iteration 19, loss = 0.53341029
Iteration 20, loss = 0.52970484
Iteration 21, loss = 0.52593153
Iteration 22, loss = 0.52238050
Iteration 23, loss = 0.51887322
Iteration 24, loss = 0.51564052
Iteration 25, loss = 0.51254839
Iteration 26, loss = 0.50943977
Iteration 27, loss = 0.50692739
Iteration 28, loss = 0.50428003
Iteration 29, loss = 0.50175153
Iteration 30, loss = 0.49930392
Iteration 31, loss = 0.49708073
Iteration 32, loss = 0.49488137
Iteration 33, loss = 0.49278574
Iteration 34, loss = 0.49085383
Iteration 35, loss = 0.48894156
Iteration 36, loss = 0.48716814
Iteration 37, loss = 0.48543209
Iteration 38, loss = 0.48375614
Iteration 39, loss = 0.48236056
Iteration 40, loss = 0.48083073
Iteration 41, loss = 0.47942386
Iteration 42, loss = 0.47802468
Iteration 43, loss = 0.47673178
Iteration 44, loss = 0.47548779
Iteration 45, loss = 0.47426049
Iteration 46, loss = 0.47306398
Iteration 47, loss = 0.47194371
Iteration 48, loss = 0.47096075
Iteration 49, loss = 0.46985900
Iteration 50, loss = 0.46880070
Iteration 51, loss = 0.46793744
Iteration 52, loss = 0.46696236
Iteration 53, loss = 0.46607602
Iteration 54, loss = 0.46517741
Iteration 55, loss = 0.46449647
Iteration 56, loss = 0.46368871
Iteration 57, loss = 0.46289937
Iteration 58, loss = 0.46236862
Iteration 59, loss = 0.46152082
Iteration 60, loss = 0.46091815
Iteration 61, loss = 0.46031177
Iteration 62, loss = 0.45967223
Iteration 63, loss = 0.45913866
Iteration 64, loss = 0.45848547
Iteration 65, loss = 0.45798934
Iteration 66, loss = 0.45748076
Iteration 67, loss = 0.45694283
Iteration 68, loss = 0.45650476
Iteration 69, loss = 0.45601960
Iteration 70, loss = 0.45555102
Iteration 71, loss = 0.45508043
Iteration 72, loss = 0.45469110
Iteration 73, loss = 0.45422464
Iteration 74, loss = 0.45377798
Iteration 75, loss = 0.45350581
Iteration 76, loss = 0.45295088
Iteration 77, loss = 0.45256567
Iteration 78, loss = 0.45221594
Iteration 79, loss = 0.45176424
Iteration 80, loss = 0.45130830
Iteration 81, loss = 0.45101273
Iteration 82, loss = 0.45059337
Iteration 83, loss = 0.45025276
Iteration 84, loss = 0.44982857
Iteration 85, loss = 0.44944955
Iteration 86, loss = 0.44911293
Iteration 87, loss = 0.44873685
Iteration 88, loss = 0.44829833
Iteration 89, loss = 0.44785448
Iteration 90, loss = 0.44770343
Iteration 91, loss = 0.44726521
Iteration 92, loss = 0.44695721
Iteration 93, loss = 0.44684215
Iteration 94, loss = 0.44630734
Iteration 95, loss = 0.44614858
Iteration 96, loss = 0.44568494
Iteration 97, loss = 0.44544247
Iteration 98, loss = 0.44504210
Iteration 99, loss = 0.44470844
Iteration 100, loss = 0.44451545
Iteration 101, loss = 0.44418774
Iteration 102, loss = 0.44394666
Iteration 103, loss = 0.44365826
Iteration 104, loss = 0.44332314
Iteration 105, loss = 0.44308928
Iteration 106, loss = 0.44290378
Iteration 107, loss = 0.44246826
Iteration 108, loss = 0.44222817
Iteration 109, loss = 0.44202937
Iteration 110, loss = 0.44173222
Iteration 111, loss = 0.44147977
Iteration 112, loss = 0.44124385
Iteration 113, loss = 0.44098218
Iteration 114, loss = 0.44079069
Iteration 115, loss = 0.44057608
Iteration 116, loss = 0.44018388
Iteration 117, loss = 0.44006225
Iteration 118, loss = 0.43965782
Iteration 119, loss = 0.43940691
Iteration 120, loss = 0.43917539
Iteration 121, loss = 0.43897304
Iteration 122, loss = 0.43882798
Iteration 123, loss = 0.43854267
Iteration 124, loss = 0.43829716
Iteration 125, loss = 0.43803582
Iteration 126, loss = 0.43778300
Iteration 127, loss = 0.43754882
Iteration 128, loss = 0.43732531
Iteration 129, loss = 0.43712739
Iteration 130, loss = 0.43689859
Iteration 131, loss = 0.43675263
Iteration 132, loss = 0.43645024
Iteration 133, loss = 0.43617851
Iteration 134, loss = 0.43586479
Iteration 135, loss = 0.43567475
Iteration 136, loss = 0.43540456
Iteration 137, loss = 0.43520968
Iteration 138, loss = 0.43497235
Iteration 139, loss = 0.43474160
Iteration 140, loss = 0.43451001
Iteration 141, loss = 0.43452008
Iteration 142, loss = 0.43409597
Iteration 143, loss = 0.43392021
Iteration 144, loss = 0.43376226
Iteration 145, loss = 0.43357371
Iteration 146, loss = 0.43341255
Iteration 147, loss = 0.43309358
Iteration 148, loss = 0.43291461
Iteration 149, loss = 0.43265375
Iteration 150, loss = 0.43247558
Iteration 151, loss = 0.43235076
Iteration 152, loss = 0.43210014
Iteration 153, loss = 0.43194749
Iteration 154, loss = 0.43174192
Iteration 155, loss = 0.43166592
Iteration 156, loss = 0.43139563
Iteration 157, loss = 0.43127768
Iteration 158, loss = 0.43114664
Iteration 159, loss = 0.43088775
Iteration 160, loss = 0.43069701
Iteration 161, loss = 0.43053896
Iteration 162, loss = 0.43034631
Iteration 163, loss = 0.43021508
Iteration 164, loss = 0.43000224
Iteration 165, loss = 0.43002911
Iteration 166, loss = 0.42987034
Iteration 167, loss = 0.42953650
Iteration 168, loss = 0.42971682
Iteration 169, loss = 0.42926273
Iteration 170, loss = 0.42916041
Iteration 171, loss = 0.42890446
Iteration 172, loss = 0.42871064
Iteration 173, loss = 0.42858214
Iteration 174, loss = 0.42840300
Iteration 175, loss = 0.42837379
Iteration 176, loss = 0.42814331
Iteration 177, loss = 0.42792916
Iteration 178, loss = 0.42774011
Iteration 179, loss = 0.42765608
Iteration 180, loss = 0.42735864
Iteration 181, loss = 0.42724366
Iteration 182, loss = 0.42712889
Iteration 183, loss = 0.42710193
Iteration 184, loss = 0.42676090
Iteration 185, loss = 0.42666751
Iteration 186, loss = 0.42660866
Iteration 187, loss = 0.42637202
Iteration 188, loss = 0.42624279
Iteration 189, loss = 0.42619894
Iteration 190, loss = 0.42601513
Iteration 191, loss = 0.42570470
Iteration 192, loss = 0.42565889
Iteration 193, loss = 0.42545617
Iteration 194, loss = 0.42534010
Iteration 195, loss = 0.42525838
Iteration 196, loss = 0.42497513
Iteration 197, loss = 0.42484661
Iteration 198, loss = 0.42472081
Iteration 199, loss = 0.42466116
Iteration 200, loss = 0.42438245
Iteration 201, loss = 0.42425474
Iteration 202, loss = 0.42406393
Iteration 203, loss = 0.42396826
Iteration 204, loss = 0.42376587
Iteration 205, loss = 0.42357772
Iteration 206, loss = 0.42344138
Iteration 207, loss = 0.42337766
Iteration 208, loss = 0.42314593
Iteration 209, loss = 0.42322589
Iteration 210, loss = 0.42289172
Iteration 211, loss = 0.42263798
Iteration 212, loss = 0.42268802
Iteration 213, loss = 0.42233336
Iteration 214, loss = 0.42213398
Iteration 215, loss = 0.42199200
Iteration 216, loss = 0.42198846
Iteration 217, loss = 0.42173984
Iteration 218, loss = 0.42153415
Iteration 219, loss = 0.42143083
Iteration 220, loss = 0.42128360
Iteration 221, loss = 0.42104206
Iteration 222, loss = 0.42083389
Iteration 223, loss = 0.42073983
Iteration 224, loss = 0.42051917
Iteration 225, loss = 0.42043911
Iteration 226, loss = 0.42019579
Iteration 227, loss = 0.42007607
Iteration 228, loss = 0.41991500
Iteration 229, loss = 0.41974101
Iteration 230, loss = 0.41954605
Iteration 231, loss = 0.41939732
Iteration 232, loss = 0.41923955
Iteration 233, loss = 0.41905538
Iteration 234, loss = 0.41893196
Iteration 235, loss = 0.41881547
Iteration 236, loss = 0.41869453
Iteration 237, loss = 0.41851526
Iteration 238, loss = 0.41848941
Iteration 239, loss = 0.41822286
Iteration 240, loss = 0.41808567
Iteration 241, loss = 0.41798856
Iteration 242, loss = 0.41793147
Iteration 243, loss = 0.41781173
Iteration 244, loss = 0.41749937
Iteration 245, loss = 0.41734535
Iteration 246, loss = 0.41730939
Iteration 247, loss = 0.41720901
Iteration 248, loss = 0.41705573
Iteration 249, loss = 0.41679716
Iteration 250, loss = 0.41681690
Iteration 251, loss = 0.41656136
Iteration 252, loss = 0.41642663
Iteration 253, loss = 0.41631539
Iteration 254, loss = 0.41615180
Iteration 255, loss = 0.41613382
Iteration 256, loss = 0.41598175
Iteration 257, loss = 0.41576046
Iteration 258, loss = 0.41569118
Iteration 259, loss = 0.41556067
Iteration 260, loss = 0.41535339
Iteration 261, loss = 0.41521672
Iteration 262, loss = 0.41512734
Iteration 263, loss = 0.41496842
Iteration 264, loss = 0.41482972
Iteration 265, loss = 0.41480063
Iteration 266, loss = 0.41453855
Iteration 267, loss = 0.41443160
Iteration 268, loss = 0.41442515
Iteration 269, loss = 0.41415501
Iteration 270, loss = 0.41401415
Iteration 271, loss = 0.41397747
Iteration 272, loss = 0.41381454
Iteration 273, loss = 0.41368498
Iteration 274, loss = 0.41349548
Iteration 275, loss = 0.41349176
Iteration 276, loss = 0.41333996
Iteration 277, loss = 0.41320229
Iteration 278, loss = 0.41311690
Iteration 279, loss = 0.41305493
Iteration 280, loss = 0.41274564
Iteration 281, loss = 0.41259623
Iteration 282, loss = 0.41250404
Iteration 283, loss = 0.41227859
Iteration 284, loss = 0.41221931
Iteration 285, loss = 0.41236333
Iteration 286, loss = 0.41195128
Iteration 287, loss = 0.41189962
Iteration 288, loss = 0.41172012
Iteration 289, loss = 0.41156369
Iteration 290, loss = 0.41147267
Iteration 291, loss = 0.41135671
Iteration 292, loss = 0.41127905
Iteration 293, loss = 0.41108864
Iteration 294, loss = 0.41093311
Iteration 295, loss = 0.41080036
Iteration 296, loss = 0.41079732
Iteration 297, loss = 0.41065239
Iteration 298, loss = 0.41049595
Iteration 299, loss = 0.41028262
Iteration 300, loss = 0.41024547
Iteration 301, loss = 0.41016244
Iteration 302, loss = 0.40998156
Iteration 303, loss = 0.40997727
Iteration 304, loss = 0.40972234
Iteration 305, loss = 0.40952577
Iteration 306, loss = 0.40966390
Iteration 307, loss = 0.40947679
Iteration 308, loss = 0.40952470
Iteration 309, loss = 0.40922776
Iteration 310, loss = 0.40903975
Iteration 311, loss = 0.40896583
Iteration 312, loss = 0.40899299
Iteration 313, loss = 0.40863518
Iteration 314, loss = 0.40851093
Iteration 315, loss = 0.40843855
Iteration 316, loss = 0.40846232
Iteration 317, loss = 0.40812367
Iteration 318, loss = 0.40803964
Iteration 319, loss = 0.40800349
Iteration 320, loss = 0.40790488
Iteration 321, loss = 0.40773246
Iteration 322, loss = 0.40757091
Iteration 323, loss = 0.40747907
Iteration 324, loss = 0.40732707
Iteration 325, loss = 0.40722972
Iteration 326, loss = 0.40712031
Iteration 327, loss = 0.40702159
Iteration 328, loss = 0.40687910
Iteration 329, loss = 0.40673918
Iteration 330, loss = 0.40659585
Iteration 331, loss = 0.40652146
Iteration 332, loss = 0.40656638
Iteration 333, loss = 0.40630853
Iteration 334, loss = 0.40629728
Iteration 335, loss = 0.40592739
Iteration 336, loss = 0.40599561
Iteration 337, loss = 0.40597821
Iteration 338, loss = 0.40570054
Iteration 339, loss = 0.40549918
Iteration 340, loss = 0.40553476
Iteration 341, loss = 0.40533428
Iteration 342, loss = 0.40533656
Iteration 343, loss = 0.40507252
Iteration 344, loss = 0.40505615
Iteration 345, loss = 0.40464105
Iteration 346, loss = 0.40484441
Iteration 347, loss = 0.40462194
Iteration 348, loss = 0.40445895
Iteration 349, loss = 0.40427170
Iteration 350, loss = 0.40412494
Iteration 351, loss = 0.40402029
Iteration 352, loss = 0.40402312
Iteration 353, loss = 0.40378474
Iteration 354, loss = 0.40404882
Iteration 355, loss = 0.40375073
Iteration 356, loss = 0.40360172
Iteration 357, loss = 0.40346342
Iteration 358, loss = 0.40355108
Iteration 359, loss = 0.40321054
Iteration 360, loss = 0.40304249
Iteration 361, loss = 0.40312900
Iteration 362, loss = 0.40293999
Iteration 363, loss = 0.40288889
Iteration 364, loss = 0.40273157
Iteration 365, loss = 0.40254574
Iteration 366, loss = 0.40243536
Iteration 367, loss = 0.40231002
Iteration 368, loss = 0.40218655
Iteration 369, loss = 0.40207158
Iteration 370, loss = 0.40198020
Iteration 371, loss = 0.40183507
Iteration 372, loss = 0.40174514
Iteration 373, loss = 0.40169619
Iteration 374, loss = 0.40150255
Iteration 375, loss = 0.40147269
Iteration 376, loss = 0.40133272
Iteration 377, loss = 0.40121161
Iteration 378, loss = 0.40137590
Iteration 379, loss = 0.40097176
Iteration 380, loss = 0.40096895
Iteration 381, loss = 0.40093693
Iteration 382, loss = 0.40075226
Iteration 383, loss = 0.40059300
Iteration 384, loss = 0.40063030
Iteration 385, loss = 0.40045050
Iteration 386, loss = 0.40032691
Iteration 387, loss = 0.40018205
Iteration 388, loss = 0.40015378
Iteration 389, loss = 0.39997002
Iteration 390, loss = 0.39989071
Iteration 391, loss = 0.39979166
Iteration 392, loss = 0.39973043
Iteration 393, loss = 0.39966975
Iteration 394, loss = 0.39964655
Iteration 395, loss = 0.39944360
Iteration 396, loss = 0.39933505
Iteration 397, loss = 0.39915364
Iteration 398, loss = 0.39916485
Iteration 399, loss = 0.39899495
Iteration 400, loss = 0.39890957
Iteration 401, loss = 0.39884209
Iteration 402, loss = 0.39874175
Iteration 403, loss = 0.39861574
Iteration 404, loss = 0.39849690
Iteration 405, loss = 0.39839764
Iteration 406, loss = 0.39830201
Iteration 407, loss = 0.39820367
Iteration 408, loss = 0.39817317
Iteration 409, loss = 0.39791766
Iteration 410, loss = 0.39777845
Iteration 411, loss = 0.39786870
Iteration 412, loss = 0.39761399
Iteration 413, loss = 0.39739770
Iteration 414, loss = 0.39735474
Iteration 415, loss = 0.39739459
Iteration 416, loss = 0.39706044
Iteration 417, loss = 0.39702920
Iteration 418, loss = 0.39689817
Iteration 419, loss = 0.39680167
Iteration 420, loss = 0.39673327
Iteration 421, loss = 0.39650862
Iteration 422, loss = 0.39650218
Iteration 423, loss = 0.39635834
Iteration 424, loss = 0.39620506
Iteration 425, loss = 0.39606984
Iteration 426, loss = 0.39616202
Iteration 427, loss = 0.39595122
Iteration 428, loss = 0.39578894
Iteration 429, loss = 0.39566059
Iteration 430, loss = 0.39556956
Iteration 431, loss = 0.39546748
Iteration 432, loss = 0.39528477
Iteration 433, loss = 0.39516575
Iteration 434, loss = 0.39517840
Iteration 435, loss = 0.39512968
Iteration 436, loss = 0.39504373
Iteration 437, loss = 0.39485217
Iteration 438, loss = 0.39468137
Iteration 439, loss = 0.39454842
Iteration 440, loss = 0.39447892
Iteration 441, loss = 0.39442014
Iteration 442, loss = 0.39427241
Iteration 443, loss = 0.39435320
Iteration 444, loss = 0.39427602
Iteration 445, loss = 0.39404533
Iteration 446, loss = 0.39396398
Iteration 447, loss = 0.39376052
Iteration 448, loss = 0.39404873
Iteration 449, loss = 0.39365031
Iteration 450, loss = 0.39352395
Iteration 451, loss = 0.39340295
Iteration 452, loss = 0.39342685
Iteration 453, loss = 0.39323026
Iteration 454, loss = 0.39311197
Iteration 455, loss = 0.39317254
Iteration 456, loss = 0.39292723
Iteration 457, loss = 0.39286346
Iteration 458, loss = 0.39270492
Iteration 459, loss = 0.39264426
Iteration 460, loss = 0.39256592
Iteration 461, loss = 0.39255292
Iteration 462, loss = 0.39241864
Iteration 463, loss = 0.39229726
Iteration 464, loss = 0.39216011
Iteration 465, loss = 0.39216147
Iteration 466, loss = 0.39199793
Iteration 467, loss = 0.39189496
Iteration 468, loss = 0.39202207
Iteration 469, loss = 0.39186721
Iteration 470, loss = 0.39162792
Iteration 471, loss = 0.39189530
Iteration 472, loss = 0.39155348
Iteration 473, loss = 0.39148863
Iteration 474, loss = 0.39132693
Iteration 475, loss = 0.39120450
Iteration 476, loss = 0.39115472
Iteration 477, loss = 0.39111521
Iteration 478, loss = 0.39093589
Iteration 479, loss = 0.39086243
Iteration 480, loss = 0.39081884
Iteration 481, loss = 0.39091954
Iteration 482, loss = 0.39078545
Iteration 483, loss = 0.39054103
Iteration 484, loss = 0.39045631
Iteration 485, loss = 0.39041501
Iteration 486, loss = 0.39028315
Iteration 487, loss = 0.39032280
Iteration 488, loss = 0.39020125
Iteration 489, loss = 0.39006708
Iteration 490, loss = 0.38997255
Iteration 491, loss = 0.38996461
Iteration 492, loss = 0.38992064
Iteration 493, loss = 0.38991955
Iteration 494, loss = 0.38957616
Iteration 495, loss = 0.38944079
Iteration 496, loss = 0.38936274
Iteration 497, loss = 0.38940848
Iteration 498, loss = 0.38950749
Iteration 499, loss = 0.38911817
Iteration 500, loss = 0.38899211
Iteration 501, loss = 0.38927839
Iteration 502, loss = 0.38888145
Iteration 503, loss = 0.38877576
Iteration 504, loss = 0.38871568
Iteration 505, loss = 0.38865092
Iteration 506, loss = 0.38844685
Iteration 507, loss = 0.38840947
Iteration 508, loss = 0.38850847
Iteration 509, loss = 0.38830416
Iteration 510, loss = 0.38813663
Iteration 511, loss = 0.38819417
Iteration 512, loss = 0.38805369
Iteration 513, loss = 0.38792316
Iteration 514, loss = 0.38813819
Iteration 515, loss = 0.38776614
Iteration 516, loss = 0.38777234
Iteration 517, loss = 0.38769536
Iteration 518, loss = 0.38762725
Iteration 519, loss = 0.38745282
Iteration 520, loss = 0.38731911
Iteration 521, loss = 0.38733033
Iteration 522, loss = 0.38738373
Iteration 523, loss = 0.38719803
Iteration 524, loss = 0.38707333
Iteration 525, loss = 0.38709143
Iteration 526, loss = 0.38699652
Iteration 527, loss = 0.38690372
Iteration 528, loss = 0.38675337
Iteration 529, loss = 0.38677610
Iteration 530, loss = 0.38669257
Iteration 531, loss = 0.38662368
Iteration 532, loss = 0.38643181
Iteration 533, loss = 0.38637671
Iteration 534, loss = 0.38643836
Iteration 535, loss = 0.38627002
Iteration 536, loss = 0.38634998
Iteration 537, loss = 0.38630957
Iteration 538, loss = 0.38613311
Iteration 539, loss = 0.38648284
Iteration 540, loss = 0.38619751
Iteration 541, loss = 0.38582314
Iteration 542, loss = 0.38573415
Iteration 543, loss = 0.38576961
Iteration 544, loss = 0.38560028
Iteration 545, loss = 0.38544150
Iteration 546, loss = 0.38549446
Iteration 547, loss = 0.38553829
Iteration 548, loss = 0.38534820
Iteration 549, loss = 0.38541473
Iteration 550, loss = 0.38545294
Iteration 551, loss = 0.38543784
Iteration 552, loss = 0.38509859
Iteration 553, loss = 0.38497551
Iteration 554, loss = 0.38501393
Iteration 555, loss = 0.38515236
Iteration 556, loss = 0.38465915
Iteration 557, loss = 0.38479719
Iteration 558, loss = 0.38488807
Iteration 559, loss = 0.38480126
Iteration 560, loss = 0.38468672
Iteration 561, loss = 0.38451053
Iteration 562, loss = 0.38447786
Iteration 563, loss = 0.38443681
Iteration 564, loss = 0.38439356
Iteration 565, loss = 0.38458541
Iteration 566, loss = 0.38412699
Iteration 567, loss = 0.38424583
Iteration 568, loss = 0.38405173
Iteration 569, loss = 0.38396351
Iteration 570, loss = 0.38399268
Iteration 571, loss = 0.38399967
Iteration 572, loss = 0.38388464
Iteration 573, loss = 0.38373993
Iteration 574, loss = 0.38368941
Iteration 575, loss = 0.38354264
Iteration 576, loss = 0.38364000
Iteration 577, loss = 0.38346492
Iteration 578, loss = 0.38341210
Iteration 579, loss = 0.38336971
Iteration 580, loss = 0.38333911
Iteration 581, loss = 0.38328901
Iteration 582, loss = 0.38312714
Iteration 583, loss = 0.38304999
Iteration 584, loss = 0.38301725
Iteration 585, loss = 0.38295824
Iteration 586, loss = 0.38292182
Iteration 587, loss = 0.38279348
Iteration 588, loss = 0.38284362
Iteration 589, loss = 0.38277630
Iteration 590, loss = 0.38264573
Iteration 591, loss = 0.38263558
Iteration 592, loss = 0.38257625
Iteration 593, loss = 0.38243813
Iteration 594, loss = 0.38246797
Iteration 595, loss = 0.38228439
Iteration 596, loss = 0.38225069
Iteration 597, loss = 0.38218767
Iteration 598, loss = 0.38233653
Iteration 599, loss = 0.38227094
Iteration 600, loss = 0.38203880
Iteration 601, loss = 0.38208817
Iteration 602, loss = 0.38189637
Iteration 603, loss = 0.38190654
Iteration 604, loss = 0.38195530
Iteration 605, loss = 0.38181494
Iteration 606, loss = 0.38175474
Iteration 607, loss = 0.38163791
Iteration 608, loss = 0.38156299
Iteration 609, loss = 0.38148274

In [12]:
print('Number of Layer =', mlp.n_layers_)
print('Number of Iteration =', mlp.n_iter_)
print('Current loss computed with the loss function =', mlp.loss_)

Number of Layer = 3
Number of Iteration = 618
Current loss computed with the loss function = 0.3811077272445009

In [13]:
# Import the metrics class
from sklearn import metrics


# Confussion Matrix
cnf_matrixmlp = metrics.confusion_matrix(y_test, y_predmlp)
cnf_matrixmlp

array([[4047,  627],
       [ 736,  929]])

In [14]:
# Show the Accuracy, Precision, Recall, F1, etc.
acc_mlp = metrics.accuracy_score(y_test, y_predmlp)
prec_mlp = metrics.precision_score(y_test, y_predmlp)
rec_mlp = metrics.recall_score(y_test, y_predmlp)
f1_mlp = metrics.f1_score(y_test, y_predmlp)
kappa_mlp = metrics.cohen_kappa_score(y_test, y_predmlp)

print("Accuracy:", acc_mlp)
print("Precision:", prec_mlp)
print("Recall:", rec_mlp)
print("F1 Score:", f1_mlp)
print("Cohens Kappa Score:", kappa_mlp)

Accuracy: 0.7849818583372772
Precision: 0.5970437017994858
Recall: 0.557957957957958
F1 Score: 0.5768394908413537
Cohens Kappa Score: 0.43293462468494115

## Q1

**Split Data:** Splitting the dataset into two parts: the training set and the test set.

- `X_train` and `X_tes`t will contain the features (independent variables) for the training and testing datasets, respectively.
- `y_train` and `y_test` will contain the corresponding target labels (the 'Churn' column in this case) for the training and testing datasets, respectively.
- `shuffle=True` ensures that the data is randomly shuffled before splitting.
- `test_size=0.3` means that 30% of the data will be used for testing, and 70% for training.
- `random_state=1` sets a seed for the random number generator to ensure reproducibility. Different values will result in different random splits

**Confussion Matrix:** A table that is often used to describe the performance of a classification model. It shows the counts of True Positives (TP), True Negatives (TN), False Positives (FP), and False Negatives (FN).

- `y_test` contains the true labels of the test dataset
- `y_predmlp` contains the predicated labels generated by the MLPClassifier

**Other definitions:**
- `accuracy_score` calculates the accuracy of the model, which is the proportion of correctly predicted instances.
- `precision_score` calculates precision, which is the ratio of true positives to the total predicted positives. It measures how many of the predicted positive cases were correct.
- `recall_score` calculates recall, which is the ratio of true positives to the total actual positives. It measures how many of the actual positive cases were correctly predicted.
- `f1_score` calculates the F1 score, which is the harmonic mean of precision and recall. It provides a balance between precision and recall.
- `cohen_kappa_score` calculates Cohen's Kappa Score, which measures the agreement between the predicted and actual labels while taking into account the possibility of agreement by chance.

## Q2

Main observations:
1. Number of Iteration increased on the 10%, this is because training on smaller dataset can make convergence slower.
2. Confusion matrix shows different counts because model's predications are different when trained on smaller dataset.
3. Accuracy, Precision, Recall, F1 and CKS a bit better on the larger training dataset.

In [15]:
# Import libraries
import pandas as pd
from sklearn.datasets import make_regression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_squared_error

# Load the dataset with TotalCharges as the target variable
url = 'https://raw.githubusercontent.com/rc-dbe/bigdatacertification/master/dataset/churn_trasnsformed_new.csv'
df = pd.read_csv(url, sep=',')

# Remove "Unnamed: 0" column
df = df.drop("Unnamed: 0", axis=1)

# initialize min-max scaler
mm_scaler = MinMaxScaler()
column_names = df.columns.tolist()

# Transform all attributes
df[column_names] = mm_scaler.fit_transform(df[column_names])
df.sort_index(inplace=True)

# Set TotalCharges as the target variable
target = 'TotalCharges'
feature_cols = [col for col in df.columns if col != target]

X = df[feature_cols]
y = df[[target]]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

# Train a Linear Regression model
regressor = GradientBoostingRegressor()
model = MultiOutputRegressor(regressor)
model.fit(X_train, y_train)

# Prediction to Test Dataset
y_pred = model.predict(X_test)

# Calculate the mean squared error (MSE)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error (MSE):", mse)

Mean Squared Error (MSE): 0.03029819947254036